name: VelocityManager
version: "${project.version}"
main: de.epsdev.velocitymanager.spigot.VelocityManager
load: POSTWORLD
authors: [EliasSchramm]
website: https://gitlab.eps-dev.de/Elias/velocitymanager
