stages:
    - pre-build
    - build

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

build_lib:
    image: maven:3.8.4-eclipse-temurin-16
    stage: pre-build
    script:
        - cd lib && mvn clean install

build_spigot:
    image: maven:3.8.4-eclipse-temurin-16
    stage: build
    needs:
      - build_lib
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - spigot/target/*.jar
    script:
        - cd spigot && mvn clean package

build_velocity:
    image: maven:3.8.4-eclipse-temurin-16
    stage: build
    needs:
      - build_lib
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - velocity/target/*.jar
    script:
        - cd velocity && mvn clean package
