stages:
    - pre-build
    - build

variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

build_lib:
    image: maven:3.8.4-eclipse-temurin-16
    stage: pre-build
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - .m2/repository
    script:
        - cd lib && mvn clean install

install_npm_dependencies:
    image: node:14-alpine
    stage: pre-build
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - api/node_modules
    script:
        - cd api && npm i

build_spigot:
    image: maven:3.8.4-eclipse-temurin-16
    stage: build
    needs:
        - build_lib
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - spigot/target/*.jar
    script:
        - cd spigot && mvn clean package

build_velocity:
    image: maven:3.8.4-eclipse-temurin-16
    stage: build
    needs:
        - build_lib
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - velocity/target/*.jar
    script:
        - cd velocity && mvn clean package

build_api:
    image: node:14-alpine
    stage: build
    needs:
        - install_npm_dependencies
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - api/index.js
    script:
        - cd api
        - npm run build
        - esbuild ./dist/index.js --bundle --outfile=index.js --platform=node
