stages:
    - build

build_spigot:
    image: maven:3.8.4-eclipse-temurin-16
    stage: build
    artifacts:
        untracked: false
        expire_in: 7 days
        paths:
            - spigot/target/*.jar
    script:
        - cd lib && mvn clean install
        - cd ../spigot && mvn clean package
